/*
Author    :	Joshua Musyoka
Title     :	Techpitch system
Date      :	02 Oct 2024
Company   : Techxal
Database  :	tpsys
*/




------------------------------------------------------------*/
--    USERS - admins
------------------------------------------------------------*/

DROP TABLE IF EXISTS user;
CREATE TABLE user (
  userId INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  email VARCHAR(250) NULL DEFAULT NULL UNIQUE,
  phone BIGINT NULL DEFAULT NULL UNIQUE,
  fname VARCHAR(250) NULL DEFAULT NULL,
  lname VARCHAR(250) NULL DEFAULT NULL,
  active TINYINT NULL DEFAULT NULL,
  passreset TINYINT NULL DEFAULT NULL,
  pass VARCHAR(250) NULL DEFAULT NULL, 
  pCode INT NULL DEFAULT NULL,
  eCode VARCHAR(250) NULL DEFAULT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (userId)
  -- FOREIGN KEY (customertypeId) REFERENCES customertype(typeId) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;











------------------------------------------------------------*/
--    CUSTOMER
------------------------------------------------------------*/

---------   activation type
DROP TABLE IF EXISTS customertype;
CREATE TABLE customertype (
  typeId TINYINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  type VARCHAR(255) NOT NULL UNIQUE,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (typeId)
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

---------   customers
DROP TABLE IF EXISTS customer;
CREATE TABLE customer (
  customerId INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  email VARCHAR(250) NULL DEFAULT NULL UNIQUE,
  phone BIGINT NULL DEFAULT NULL UNIQUE,
  cname VARCHAR(250) NULL DEFAULT NULL,
  fname VARCHAR(250) NULL DEFAULT NULL,
  lname VARCHAR(250) NULL DEFAULT NULL,
  active TINYINT NULL DEFAULT NULL,
  passreset TINYINT NULL DEFAULT NULL,
  pass VARCHAR(250) NULL DEFAULT NULL, 
  pCode INT NULL DEFAULT NULL,
  eCode VARCHAR(250) NULL DEFAULT NULL,
  customertypeId TINYINT UNSIGNED NOT NULL DEFAULT 1,
  verificationType ENUM('phone','email') NOT NULL,
  verificationTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (customerId),
  FOREIGN KEY (customertypeId) REFERENCES customertype(typeId) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;
ALTER TABLE customer
  ADD COLUMN verified TINYINT NULL DEFAULT 0 AFTER active;
ALTER TABLE customer
  ADD COLUMN cAddress VARCHAR(250) NULL DEFAULT NULL AFTER customertypeId;
ALTER TABLE customer
  ADD COLUMN img VARCHAR(250) NULL DEFAULT NULL AFTER lname;
ALTER TABLE customer
  ADD COLUMN nationalId VARCHAR(10) NULL DEFAULT NULL AFTER lname;

-- self registered customers will have a default grouping
DROP TABLE IF EXISTS groupings;
CREATE TABLE groupings (
    groupId INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    adminId INT UNSIGNED NOT NULL UNIQUE,
    units INT UNSIGNED NOT NULL DEFAULT 0,
    active ENUM('1','0') DEFAULT '0',
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (adminId) REFERENCES customer (customerId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;  
ALTER TABLE groupings
  ADD COLUMN units INT UNSIGNED NOT NULL DEFAULT 0 AFTER adminId;


-- cuctomers assigned to a group
DROP TABLE IF EXISTS participant;
CREATE TABLE participant (
  groupId INT UNSIGNED NOT NULL,
  customerId INT UNSIGNED NOT NULL,
  active ENUM('1','0') DEFAULT '1',
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY (groupId,customerId),
  FOREIGN KEY (groupId) REFERENCES groupings (groupId) ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY (customerId) REFERENCES customer (customerId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;









------------------------------------------------------------*/
--    TEMPLATE
------------------------------------------------------------*/

-- Template
DROP TABLE IF EXISTS template;
CREATE TABLE template (
    templateId INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    title VARCHAR(255) NULL DEFAULT NULL,
    template TEXT NULL DEFAULT NULL,
    customerId INT UNSIGNED NULL DEFAULT NULL,
    groupId INT UNSIGNED NULL DEFAULT NULL,
    active ENUM('1','0') DEFAULT '1',
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (templateId),
    UNIQUE KEY (groupId,title),
    UNIQUE KEY (groupId,template),
    FOREIGN KEY (groupId) REFERENCES groupings (groupId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (customerId) REFERENCES customer (customerId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;










------------------------------------------------------------*/
--    ALPHANUMERIC 
------------------------------------------------------------*/

-- alphanumeric
DROP TABLE IF EXISTS alphanumeric;
CREATE TABLE alphanumeric (
    alphanumericId INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    title VARCHAR(255) NOT NULL UNIQUE,
    -- content VARCHAR(1000) NULL DEFAULT NULL,
    -- typeId TINYINT UNSIGNED NOT NULL DEFAULT 1,
    -- statusId TINYINT UNSIGNED NOT NULL DEFAULT 1,
    userId INT UNSIGNED NULL DEFAULT NULL,
    customerId INT UNSIGNED NULL DEFAULT NULL,
    groupId INT UNSIGNED NULL DEFAULT NULL,
    -- units INT UNSIGNED NOT NULL DEFAULT 0,
    active TINYINT(1) DEFAULT 1,
    -- posteddate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- delivered ENUM('1','0') DEFAULT '0',
    -- deliveredTime TIMESTAMP NULL DEFAULT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (alphanumericId),
    -- FOREIGN KEY (typeId) REFERENCES messagetype (typeId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    -- FOREIGN KEY (statusId) REFERENCES messagestatus (statusId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (groupId) REFERENCES groupings (groupId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (customerId) REFERENCES customer (customerId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (userId) REFERENCES user (userId) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;
ALTER TABLE alphanumeric MODIFY active TINYINT(1) DEFAULT 1;





------------------------------------------------------------*/
--    SHORTCODE
------------------------------------------------------------*/

-- shortcode
DROP TABLE IF EXISTS shortcode;
CREATE TABLE shortcode (
    shortcodeId INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    shortcode INT NOT NULL UNIQUE,
    userId INT UNSIGNED NULL DEFAULT NULL,
    -- customerId INT UNSIGNED NULL DEFAULT NULL,
    -- groupId INT UNSIGNED NULL DEFAULT NULL,
    active ENUM('1','0') DEFAULT '1',
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (shortcodeId),
    -- FOREIGN KEY (groupId) REFERENCES groupings (groupId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    -- FOREIGN KEY (customerId) REFERENCES customer (customerId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (userId) REFERENCES user (userId) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- offercode
DROP TABLE IF EXISTS offercode;
CREATE TABLE offercode (
    offercodeId INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    offercode VARCHAR(255) NOT NULL UNIQUE,
    offername VARCHAR(255) NOT NULL UNIQUE,
    shortcodeId INT UNSIGNED NOT NULL,
    userId INT UNSIGNED NOT NULL,
    groupId INT UNSIGNED NOT NULL,
    active ENUM('1','0') DEFAULT '1',
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (offercodeId),
    FOREIGN KEY (shortcodeId) REFERENCES shortcode (shortcodeId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (userId) REFERENCES user (userId) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (groupId) REFERENCES groupings (groupId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;
ALTER TABLE offercode
  ADD COLUMN offername VARCHAR(100) NOT NULL AFTER offercode;

-- keywords
DROP TABLE IF EXISTS offercodekeyword;
CREATE TABLE offercodekeyword (
    keywordId INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    keyword VARCHAR(255) NOT NULL,
    offercodeId VARCHAR(255) NULL DEFAULT NULL,
    shortcodeId INT UNSIGNED NULL DEFAULT NULL,
    userId INT UNSIGNED NULL DEFAULT NULL,
    groupId INT UNSIGNED NULL DEFAULT NULL,
    active ENUM('1','0') DEFAULT '1',
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (keywordId),
    UNIQUE KEY (keyword,offercodeId),
    FOREIGN KEY (shortcodeId) REFERENCES shortcode (shortcodeId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (userId) REFERENCES user (userId) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (groupId) REFERENCES groupings (groupId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;


-- subscribers
DROP TABLE IF EXISTS offercodesubscriber;
CREATE TABLE offercodesubscriber (
    subscriberId INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    subscriber BIGINT UNSIGNED NOT NULL,
    offercodeId INT UNSIGNED NOT NULL,
    shortcodeId INT UNSIGNED NOT NULL,
    userId INT UNSIGNED NULL DEFAULT NULL,
    groupId INT UNSIGNED NOT NULL,
    active ENUM('1','0') DEFAULT '1',
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (subscriberId),
    UNIQUE KEY (subscriber,offercodeId),
    FOREIGN KEY (offercodeId) REFERENCES offercode (offercodeId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (shortcodeId) REFERENCES shortcode (shortcodeId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (userId) REFERENCES user (userId) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (groupId) REFERENCES groupings (groupId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- shortcodes [ 6782, 8299 ]

-- keywords 
  -- 6782 [ [nyama, linkid] [mkate,linkid] ]
  -- 8299 [ bible, cartoon ]

-- contacts
  -- 6782 [ nyama, mkate ]
    -- [ 0715003414, 011510030 ]
  -- 8299 [ bible, cartoon ]
    -- [ 0715003414, 011510030 ]











------------------------------------------------------------*/
--    MESSAGE
------------------------------------------------------------*/

DROP TABLE IF EXISTS messagetype;
CREATE TABLE messagetype (
  typeId TINYINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  type VARCHAR(255) NOT NULL UNIQUE,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (typeId)
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- 'pending', 'queued', 'processing', 'sent', 'failed'
DROP TABLE IF EXISTS messagestatus;
CREATE TABLE messagestatus (
  statusId TINYINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  status VARCHAR(255) NOT NULL UNIQUE,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (statusId)
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- 'draft', 'approved', 'confirmed'
DROP TABLE IF EXISTS messageapprovalstatus;
CREATE TABLE messageapprovalstatus (
  statusId TINYINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  status VARCHAR(255) NOT NULL UNIQUE,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (statusId)
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- messages
DROP TABLE IF EXISTS messages;
CREATE TABLE messages (
    messageId INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    title VARCHAR(255) NULL DEFAULT NULL,
    content TEXT NULL DEFAULT NULL,
    typeId TINYINT UNSIGNED NOT NULL DEFAULT 1,
    statusId TINYINT UNSIGNED NOT NULL DEFAULT 1,
    approvalstatusId TINYINT UNSIGNED NOT NULL DEFAULT 1,
    adminId INT UNSIGNED NULL DEFAULT NULL,
    customerId INT UNSIGNED NULL DEFAULT NULL,
    groupId INT UNSIGNED NULL DEFAULT NULL,
    alphanumericId INT UNSIGNED NOT NULL,
    units INT UNSIGNED NOT NULL DEFAULT 0,
    totalRecipients INT UNSIGNED NOT NULL DEFAULT 0,
    successfulSends INT UNSIGNED NOT NULL DEFAULT 0,
    failedSends INT UNSIGNED NOT NULL DEFAULT 0,
    scheduled_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delivered ENUM('1','0') DEFAULT '0',
    deliveredTime TIMESTAMP NULL DEFAULT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (messageId),
    FOREIGN KEY (typeId) REFERENCES messagetype (typeId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (statusId) REFERENCES messagestatus (statusId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (approvalstatusId) REFERENCES messageapprovalstatus (statusId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (adminId) REFERENCES customer (customerId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (customerId) REFERENCES customer (customerId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (groupId) REFERENCES groupings (groupId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (alphanumericId) REFERENCES alphanumeric (alphanumericId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;
ALTER TABLE `tpsys`.`messages` 
  CHANGE COLUMN `scheduled_time` `scheduled_time` TIMESTAMP NULL DEFAULT NULL ;
ALTER TABLE messages
  ADD COLUMN reference VARCHAR(100) NULL DEFAULT NULL AFTER groupId,
  ADD UNIQUE KEY (reference,groupId);
ALTER TABLE messages
  ADD COLUMN custom ENUM('0', '1') DEFAULT '0' AFTER statusId;
ALTER TABLE messages
  ADD COLUMN recurrenceType ENUM('once', 'daily', 'weekly', 'monthly', 'annually') NOT NULL DEFAULT 'once' AFTER scheduled_time;

-- Messages Recipients
DROP TABLE IF EXISTS messagesRecipients;
CREATE TABLE messagesRecipients (
    recipientId BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    messageId INT UNSIGNED NOT NULL,
    phone BIGINT UNSIGNED NOT NULL,
    fname VARCHAR(255) NULL DEFAULT NULL,
    lname VARCHAR(255) NULL DEFAULT NULL,
    statusId TINYINT UNSIGNED NOT NULL DEFAULT 1,
    sentAt TIMESTAMP NULL DEFAULT NULL,
    deliveredAt TIMESTAMP NULL DEFAULT NULL,
    retryCount SMALLINT DEFAULT 0,
    successMessage VARCHAR(255),
    errorMessage VARCHAR(255),
    blocked ENUM('0', '1') DEFAULT '0',
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (recipientId),
    UNIQUE KEY (messageId,phone),
    FOREIGN KEY (messageId) REFERENCES messages (messageId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (statusId) REFERENCES messagestatus (statusId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;


ALTER TABLE messagesRecipients
  ADD COLUMN statusId TINYINT UNSIGNED NOT NULL DEFAULT 1 AFTER phone,
  ADD FOREIGN KEY (statusId) REFERENCES messagestatus (statusId) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `tpsys`.`messagesRecipients` 
  DROP COLUMN `deliveryStatus`;
ALTER TABLE messagesRecipients
  ADD COLUMN blocked ENUM('0', '1') DEFAULT '0' AFTER errorMessage;
ALTER TABLE messagesRecipients
  ADD COLUMN fname VARCHAR(255) NULL DEFAULT NULL AFTER phone,
  ADD COLUMN lname VARCHAR(255) NULL DEFAULT NULL AFTER fname;

-- Contact groups table
DROP TABLE IF EXISTS contactGroups;
CREATE TABLE contactGroups (
    groupId BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    pgroupId INT UNSIGNED NULL DEFAULT NULL,
    title VARCHAR(255) NOT NULL,
    descrp VARCHAR(1000),
    active ENUM('1','0') DEFAULT '1',
    customerId INT UNSIGNED NULL DEFAULT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (groupId),
    FOREIGN KEY (pgroupId) REFERENCES groupings (groupId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (customerId) REFERENCES customer (customerId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;
ALTER TABLE `tpsys`.`contactGroups` 
CHANGE COLUMN `active` `active` ENUM('1', '0') NULL DEFAULT '1' ;

DROP TABLE IF EXISTS recurrenceRules;
CREATE TABLE recurrenceRules (
    ruleId BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    messageId INT UNSIGNED NOT NULL,
    dayWeek TINYINT,       -- 0=Sunday to 6=Saturday (weekly)
    dayMonth TINYINT,      -- for monthly or annual
    monthYear TINYINT,     -- for annual
    deliveryTime TIME,                 -- time of the day to trigger
    FOREIGN KEY (messageId) REFERENCES messages (messageId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

CREATE TABLE recurrenceLogs (
    logId BIGINT PRIMARY KEY AUTO_INCREMENT,
    messageId INT UNSIGNED NOT NULL,
    sent_at DATETIME,
    status ENUM('sent', 'failed', 'retry') DEFAULT 'sent',
    response TEXT,
    FOREIGN KEY (messageId) REFERENCES messages (messageId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;


-- Contacts in groups
DROP TABLE IF EXISTS groupContacts;
CREATE TABLE groupContacts (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    groupId BIGINT UNSIGNED NOT NULL,
    pgroupId INT UNSIGNED NULL DEFAULT NULL,
    phone BIGINT UNSIGNED NOT NULL,
    fname VARCHAR(255) NULL DEFAULT NULL,
    lname VARCHAR(255) NULL DEFAULT NULL,
    blocked ENUM('1','0') DEFAULT '0',
    active ENUM('1','0') DEFAULT '1',
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY (groupId,phone),
    FOREIGN KEY (groupId) REFERENCES contactGroups(groupId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (pgroupId) REFERENCES groupings (groupId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

ALTER TABLE `tpsys`.`groupContacts` 
  CHANGE COLUMN `active` `active` ENUM('1', '0') NULL DEFAULT '1' ;
ALTER TABLE `tpsys`.`groupContacts` 
  ADD COLUMN `blocked` ENUM('1', '0') NULL DEFAULT '0' AFTER lname;
ALTER TABLE groupContacts
  ADD COLUMN groupContactId BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  ADD UNIQUE KEY (groupContactId);
ALTER TABLE `tpsys`.`groupContacts` 
CHANGE COLUMN `groupContactId` `groupContactId` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

-- message recepient groups
DROP TABLE IF EXISTS messagesRecipientGroup;
CREATE TABLE messagesRecipientGroup (
    messageId INT UNSIGNED NOT NULL,
    groupId BIGINT UNSIGNED NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY (messageId,groupId),
    FOREIGN KEY (messageId) REFERENCES messages (messageId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (groupId) REFERENCES contactGroups (groupId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;












------------------------------------------------------------*/
--    Payments
------------------------------------------------------------*/


-- payment mode
DROP TABLE IF EXISTS paymentmode;
CREATE TABLE paymentmode (
  modeId TINYINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  mode VARCHAR(255) NOT NULL UNIQUE,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (modeId)
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- payment status
DROP TABLE IF EXISTS paymentstatus;
CREATE TABLE paymentstatus (
  statusId TINYINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  status VARCHAR(255) NOT NULL UNIQUE,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (statusId)
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- payments
DROP TABLE IF EXISTS payments;
CREATE TABLE payments (
    paymentId INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    fname VARCHAR(255) NULL DEFAULT NULL,
    mname VARCHAR(255) NULL DEFAULT NULL,
    lname VARCHAR(255) NULL DEFAULT NULL,
    modeId TINYINT UNSIGNED NOT NULL DEFAULT 1,
    statusId TINYINT UNSIGNED NOT NULL DEFAULT 1,
    adminId INT UNSIGNED NULL DEFAULT NULL,
    customerId INT UNSIGNED NULL DEFAULT NULL,
    groupId INT UNSIGNED NULL DEFAULT NULL,
    amount DOUBLE UNSIGNED NOT NULL DEFAULT 0,
    units INT UNSIGNED NOT NULL DEFAULT 0,
    phone VARCHAR(100) NULL DEFAULT NULL,
    reference VARCHAR(255) NULL DEFAULT NULL,
    referenceI VARCHAR(255) NULL DEFAULT NULL,
    referenceII VARCHAR(255) NULL DEFAULT NULL,
    ResponseCode VARCHAR(255) NULL DEFAULT NULL,
    ResponseDescription VARCHAR(255) NULL DEFAULT NULL,
    thirdpartyTime TIMESTAMP NULL DEFAULT NULL,
    descrp VARCHAR(500) NULL DEFAULT NULL,
    posted ENUM('1','0') DEFAULT '0',
    posteddate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (paymentId),
    UNIQUE KEY (modeId,reference),
    FOREIGN KEY (modeId) REFERENCES paymentmode (modeId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (statusId) REFERENCES paymentstatus (statusId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (groupId) REFERENCES groupings (groupId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (customerId) REFERENCES customer (customerId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (adminId) REFERENCES users (userId) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

ALTER TABLE payments
  DROP FOREIGN KEY adminId;

ALTER TABLE payments
ADD FOREIGN KEY (adminId) REFERENCES users (userId)
  ON DELETE RESTRICT
  ON UPDATE CASCADE;

-- pricings
DROP TABLE IF EXISTS pricing;
CREATE TABLE pricing (
  priceId TINYINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  pFrom INT UNSIGNED NOT NULL DEFAULT 0,
  pTo INT UNSIGNED NOT NULL DEFAULT 0,
  price DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0.0,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (priceId)
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS groupunitbalance;
CREATE TABLE groupunitbalance (
  tranId INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  groupId INT UNSIGNED NOT NULL,
  paymentId INT UNSIGNED NULL DEFAULT NULL,
  messageId INT UNSIGNED NULL DEFAULT NULL,
  reference VARCHAR(100) NULL DEFAULT NULL UNIQUE,
  openingbalance INT UNSIGNED NOT NULL DEFAULT 0,
  increase INT UNSIGNED NOT NULL DEFAULT 0,
  decrease INT UNSIGNED NOT NULL DEFAULT 0,
  closingbalance INT UNSIGNED NOT NULL DEFAULT 0,
  active ENUM('1','0') DEFAULT '1',
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (tranId),
  UNIQUE KEY (groupId,paymentId),
  UNIQUE KEY (groupId,messageId),
  FOREIGN KEY (groupId) REFERENCES groupings(groupId) ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY (paymentId) REFERENCES payments(paymentId) ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY (messageId) REFERENCES messages(messageId) ON DELETE RESTRICT ON UPDATE RESTRICT
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;
-- ALTER TABLE groupunitbalance
--  ADD COLUMN reference VARCHAR(100) NULL DEFAULT NULL UNIQUE AFTER messageId;

-- Trigger start
DELIMITER $$
CREATE TRIGGER trg_groups_units_after_insert
AFTER INSERT ON groupunitbalance
FOR EACH ROW
BEGIN
  UPDATE groupings 
  SET units = NEW.closingbalance 
  WHERE groupings.groupId = NEW.groupId;
END$$
DELIMITER ;
-- Trigger end












-- roles
DROP TABLE IF EXISTS roles;
CREATE TABLE roles (
  roleId INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  title VARCHAR(255) NOT NULL,
  descrp VARCHAR(1000) NULL DEFAULT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (roleId)
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- permission group
DROP TABLE IF EXISTS permsgroup;
CREATE TABLE permsgroup (
  groupId TINYINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  title VARCHAR(255) NOT NULL,
  icon VARCHAR(100) NULL DEFAULT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (groupId)
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;
ALTER TABLE permsgroup
  ADD COLUMN icon VARCHAR(100) NULL DEFAULT NULL AFTER title;

-- permissions
DROP TABLE IF EXISTS permissions;
CREATE TABLE permissions (
    permissionId INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    groupId TINYINT UNSIGNED NOT NULL,
    permission VARCHAR(255) NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (permissionId),
    FOREIGN KEY (groupId) REFERENCES permsgroup(groupId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- role permission 
DROP TABLE IF EXISTS rolepermission;
CREATE TABLE rolepermission (
    roleId INT UNSIGNED NULL DEFAULT NULL,
    permissionId INT UNSIGNED NULL DEFAULT NULL,
    active TINYINT DEFAULT '1',
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY (roleId,permissionId),
    FOREIGN KEY (roleId) REFERENCES roles (roleId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (permissionId) REFERENCES permissions (permissionId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- customer group roles
DROP TABLE IF EXISTS customersroles;
CREATE TABLE customersroles (
    roleId INT UNSIGNED NOT NULL,
    adminId INT UNSIGNED NULL DEFAULT NULL,
    customerId INT UNSIGNED NOT NULL,
    groupId INT UNSIGNED NOT NULL,
    active ENUM('1','0') DEFAULT '1',
    descrp VARCHAR(1000) NULL DEFAULT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY (roleId,customerId,groupId),
    FOREIGN KEY (roleId) REFERENCES roles (roleId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (customerId) REFERENCES customer (customerId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (groupId) REFERENCES groupings (groupId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (adminId) REFERENCES customer (customerId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;



-- user roles [ admins ]
DROP TABLE IF EXISTS usersroles;
CREATE TABLE usersroles (
    roleId INT UNSIGNED NOT NULL,
    adminId INT UNSIGNED NOT NULL,
    userId INT UNSIGNED NOT NULL,
    active ENUM('1','0') DEFAULT '1',
    descrp VARCHAR(1000) NULL DEFAULT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY (roleId,userId),
    FOREIGN KEY (roleId) REFERENCES roles (roleId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (userId) REFERENCES user (userId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (adminId) REFERENCES user (userId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;






















































-- business customers
DROP TABLE IF EXISTS xalbusiness.businessCustomers;
CREATE TABLE xalbusiness.businessCustomers (
  businessId INT UNSIGNED NOT NULL,
  customerId INT UNSIGNED NOT NULL,
  active TINYINT UNSIGNED NULL DEFAULT 1,
  adminId INT UNSIGNED NULL DEFAULT NULL,
  admin TINYINT UNSIGNED NOT NULL DEFAULT 0,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (businessId,customerId),
  UNIQUE KEY (businessId,customerId),
  FOREIGN KEY (businessId) REFERENCES businesses (businessId) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (customerId) REFERENCES customers (customerId) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (adminId) REFERENCES customers (customerId) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;


------------------------------------------------------------*/
--  Business  -  xalcustomers
------------------------------------------------------------*/
------ start
-- gender
DROP TABLE IF EXISTS xalcustomers.gender;
CREATE TABLE xalcustomers.gender (
  genderId TINYINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  gender VARCHAR(50) NOT NULL UNIQUE,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (genderId)
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- citizen
DROP TABLE IF EXISTS xalcustomers.citizen;
CREATE TABLE xalcustomers.citizen (
  citizenId TINYINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  citizen VARCHAR(100) NOT NULL UNIQUE,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (citizenId)
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- religion
DROP TABLE IF EXISTS xalcustomers.religion;
CREATE TABLE xalcustomers.religion (
  religionId TINYINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  religion VARCHAR(255) NOT NULL UNIQUE,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (religionId)
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- occupation
DROP TABLE IF EXISTS xalcustomers.occupation;
CREATE TABLE xalcustomers.occupation (
  occupationId TINYINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  occupation VARCHAR(255) NOT NULL UNIQUE,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (occupationId)
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- relation
DROP TABLE IF EXISTS xalcustomers.relation;
CREATE TABLE xalcustomers.relation (
  relationId TINYINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  relation VARCHAR(100) NOT NULL UNIQUE,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (relationId)
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- marital
DROP TABLE IF EXISTS xalcustomers.marital;
CREATE TABLE xalcustomers.marital (
  maritalId TINYINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  marital VARCHAR(100) NOT NULL UNIQUE,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (maritalId)
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- customer
DROP TABLE IF EXISTS xalcustomers.customer;
CREATE TABLE xalcustomers.customer (
  customerId INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  email VARCHAR(250) NULL DEFAULT NULL UNIQUE,
  phone BIGINT NULL DEFAULT NULL UNIQUE,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (customerId)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- next of kin
DROP TABLE IF EXISTS xalcustomers.kin;
CREATE TABLE xalcustomers.kin (
  kinId INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  email VARCHAR(250) NULL DEFAULT NULL UNIQUE,
  phone BIGINT NULL DEFAULT NULL UNIQUE,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (kinId)
  -- FOREIGN KEY (relationId) REFERENCES relation (relationId) ON DELETE RESTRICT ON UPDATE CASCADE
  -- FOREIGN KEY (businessId) REFERENCES businesses (businessId) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- business customer
DROP TABLE IF EXISTS xalcustomers.businesscustomer;
CREATE TABLE xalcustomers.businesscustomer (
  businessId INT UNSIGNED NOT NULL,
  customerId INT UNSIGNED NOT NULL,
  fname VARCHAR(250) NULL DEFAULT NULL,
  sname VARCHAR(250) NULL DEFAULT NULL,
  lname VARCHAR(250) NULL DEFAULT NULL,
  address VARCHAR(1000) NULL DEFAULT NULL, 
  dob DATE NULL DEFAULT NULL, 
  genderId TINYINT UNSIGNED NULL DEFAULT NULL,
  citizenId TINYINT UNSIGNED NULL DEFAULT NULL,
  religionId TINYINT UNSIGNED NULL DEFAULT NULL,
  occupationId TINYINT UNSIGNED NULL DEFAULT NULL,
  maritalId TINYINT UNSIGNED NULL DEFAULT NULL,
  active TINYINT UNSIGNED NULL DEFAULT 1,
  adminId INT UNSIGNED NULL DEFAULT NULL,
  admin TINYINT UNSIGNED NOT NULL DEFAULT 0,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (businessId,customerId),
  UNIQUE KEY (businessId,customerId),
  FOREIGN KEY (genderId) REFERENCES gender (genderId) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (citizenId) REFERENCES citizen (citizenId) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (religionId) REFERENCES religion (religionId) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (occupationId) REFERENCES occupation (occupationId) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (maritalId) REFERENCES marital (maritalId) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (businessId) REFERENCES xalbusiness.businesses (businessId) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (customerId) REFERENCES customer (customerId) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (adminId) REFERENCES xalusers.users (userId) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- business customer
DROP TABLE IF EXISTS xalcustomers.customerkin;
CREATE TABLE xalcustomers.customerkin (
  kinId INT UNSIGNED NOT NULL,
  fname VARCHAR(250) NULL DEFAULT NULL,
  lname VARCHAR(250) NULL DEFAULT NULL,
  address VARCHAR(1000) NULL DEFAULT NULL, 
  dob DATE NULL DEFAULT NULL, 
  relationId TINYINT UNSIGNED NULL DEFAULT NULL,
  customerId INT UNSIGNED NOT NULL,
  businessId INT UNSIGNED NOT NULL,
  active TINYINT UNSIGNED NULL DEFAULT 1,
  adminId INT UNSIGNED NULL DEFAULT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (businessId,customerId,kinId),
  UNIQUE KEY (businessId,customerId,kinId),
  FOREIGN KEY (businessId) REFERENCES xalbusiness.businesses (businessId) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (kinId) REFERENCES kin (kinId) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (customerId) REFERENCES customer (customerId) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (adminId) REFERENCES xalusers.users (userId) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-----  end







------------------------------------------------------------*/
--  Bills  -  xalbills
------------------------------------------------------------*/
------ start

-- bills type
DROP TABLE IF EXISTS xalbills.billType;
CREATE TABLE xalbills.billType (
  typeId TINYINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  type VARCHAR(255) NOT NULL UNIQUE,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (typeId)
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- status
DROP TABLE IF EXISTS xalbills.status;
CREATE TABLE xalbills.status (
  statusId TINYINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  status VARCHAR(255) NOT NULL UNIQUE,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (statusId)
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- bills
DROP TABLE IF EXISTS xalbills.bills;
CREATE TABLE xalbills.bills (
  billId INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  billNo INT UNSIGNED NULL DEFAULT NULL,
  customerId INT UNSIGNED NULL DEFAULT NULL,
  businessId INT UNSIGNED NULL DEFAULT NULL,
  subtotal INT UNSIGNED NOT NULL DEFAULT 0,
  tax INT UNSIGNED NOT NULL DEFAULT 0,
  discount INT UNSIGNED NOT NULL DEFAULT 0,
  shipping INT UNSIGNED NOT NULL DEFAULT 0,
  descrp VARCHAR(500) NULL DEFAULT NULL,
  typeId TINYINT UNSIGNED NOT NULL DEFAULT 1,
  statusId TINYINT UNSIGNED NOT NULL DEFAULT 1,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (billId),
  UNIQUE KEY (billNo,businessId),
  FOREIGN KEY (typeId) REFERENCES xalbills.billType (typeId) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (statusId) REFERENCES xalbills.status (statusId) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (customerId) REFERENCES xalcustomers.customer (customerId) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (businessId) REFERENCES xalbusiness.businesses (businessId) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- bill items
DROP TABLE IF EXISTS xalbills.billItem;
CREATE TABLE xalbills.billItem (
  billId INT UNSIGNED NOT NULL,
  productId INT UNSIGNED NOT NULL,
  userId INT UNSIGNED NULL DEFAULT NULL,
  subtotal DOUBLE UNSIGNED NULL DEFAULT 0,
  tax DOUBLE UNSIGNED NULL DEFAULT 0,
  discount DOUBLE UNSIGNED NULL DEFAULT 0,
  total DOUBLE UNSIGNED NULL DEFAULT 0,
  quantity DOUBLE UNSIGNED NULL DEFAULT 0,
  descrp VARCHAR(500) NULL DEFAULT NULL,
  statusId TINYINT UNSIGNED NOT NULL DEFAULT 1,
  thirdpartyTime TIMESTAMP NULL DEFAULT NULL,  
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  -- PRIMARY KEY (billId),
  UNIQUE KEY (billId,productId),
  FOREIGN KEY (statusId) REFERENCES xalbills.status (statusId) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (billId) REFERENCES xalbills.bills (billId) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (productId) REFERENCES xalproducts.product (productId) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (userId) REFERENCES xalusers.users (userId) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;


------ end



------------------------------------------------------------*/
--  Payments  -  xalpayments
------------------------------------------------------------*/

-- payment mode
DROP TABLE IF EXISTS xalpayments.paymentmode;
CREATE TABLE xalpayments.paymentmode (
  modeId TINYINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  mode VARCHAR(255) NOT NULL UNIQUE,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (modeId)
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- payment status
DROP TABLE IF EXISTS xalpayments.paymentstatus;
CREATE TABLE xalpayments.paymentstatus (
  statusId TINYINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  status VARCHAR(255) NOT NULL UNIQUE,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (statusId)
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- payment type
DROP TABLE IF EXISTS xalpayments.paymentype;
CREATE TABLE xalpayments.paymentype (
  typeId TINYINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  type VARCHAR(255) NOT NULL UNIQUE,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (typeId)
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- payments
DROP TABLE IF EXISTS xalpayments.payments;
CREATE TABLE xalpayments.payments (
    paymentId INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    fname VARCHAR(255) NULL DEFAULT NULL,
    mname VARCHAR(255) NULL DEFAULT NULL,
    lname VARCHAR(255) NULL DEFAULT NULL,
    modeId TINYINT UNSIGNED NOT NULL DEFAULT 1,
    statusId TINYINT UNSIGNED NOT NULL DEFAULT 1,
    typeId TINYINT UNSIGNED NULL DEFAULT NULL,
    businessId INT UNSIGNED NULL DEFAULT NULL,
    customerId INT UNSIGNED NULL DEFAULT NULL,
    userId INT UNSIGNED NULL DEFAULT NULL,
    amount DOUBLE UNSIGNED NOT NULL,
    payee VARCHAR(255) NULL DEFAULT NULL,
    selfreference VARCHAR(255) NULL DEFAULT NULL,
    thirdpartyTime TIMESTAMP NULL DEFAULT NULL,
    thirdpartyreference VARCHAR(255) NULL DEFAULT NULL,
    mpesaMerchantRequestID VARCHAR(255) NULL DEFAULT NULL UNIQUE,
    mpesaCheckoutRequestID VARCHAR(255) NULL DEFAULT NULL UNIQUE,
    descrp VARCHAR(500) NULL DEFAULT NULL,
    thirdpartydescrp VARCHAR(500) NULL DEFAULT NULL,
    posted TINYINT UNSIGNED NOT NULL DEFAULT 0,
    posteddate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (paymentId),
    UNIQUE KEY (modeId,thirdpartyreference),
    -- UNIQUE KEY (modeId,typeId,businessId),
    FOREIGN KEY (modeId) REFERENCES xalpayments.paymentmode (modeId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (statusId) REFERENCES xalpayments.paymentstatus (statusId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (typeId) REFERENCES xalpayments.paymentype (typeId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (businessId) REFERENCES xalbusiness.businesses (businessId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (customerId) REFERENCES xalcustomers.customer (customerId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (userId) REFERENCES xalusers.users (userId) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;
ALTER TABLE xalpayments.payments
    ADD COLUMN thirdpartydescrp VARCHAR(500) NULL DEFAULT NULL AFTER descrp;
ALTER TABLE xalpayments.payments
    ADD COLUMN userId INT UNSIGNED NULL DEFAULT NULL AFTER customerId,
    ADD CONSTRAINT FOREIGN KEY (userId) REFERENCES xalusers.users (userId) ON DELETE RESTRICT ON UPDATE CASCADE;

-- payments bills or invoices
DROP TABLE IF EXISTS xalpayments.paymentsbills;
CREATE TABLE xalpayments.paymentsbills (
    paymentId INT UNSIGNED NOT NULL,
    billId INT UNSIGNED NOT NULL,
    active TINYINT UNSIGNED NOT NULL DEFAULT 1,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY (paymentId,billId),
    FOREIGN KEY (paymentId) REFERENCES xalpayments.payments (paymentId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (billId) REFERENCES xalbills.bills (billId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

------ end



------------------------------------------------------------*/
--  SMS  -  xalsms
------------------------------------------------------------*/

-- sms status processed
DROP TABLE IF EXISTS xalsms.smsstatusprocessed;
CREATE TABLE xalsms.smsstatusprocessed (
  statusId TINYINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  status VARCHAR(255) NOT NULL UNIQUE,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (statusId)
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- sms status
DROP TABLE IF EXISTS xalsms.smsstatus;
CREATE TABLE xalsms.smsstatus (
  statusId TINYINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  status VARCHAR(255) NOT NULL UNIQUE,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (statusId)
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- sms texts
DROP TABLE IF EXISTS xalsms.message;
CREATE TABLE xalsms.message (
    smsId INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    sms VARCHAR(1000) NULL DEFAULT NULL,
    statusId TINYINT UNSIGNED NOT NULL DEFAULT 1,
    statusprocessId TINYINT UNSIGNED NOT NULL DEFAULT 1,
    businessId INT UNSIGNED NOT NULL,
    userId INT UNSIGNED NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (smsId),
    FOREIGN KEY (statusId) REFERENCES xalsms.smsstatus (statusId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (statusprocessId) REFERENCES xalsms.smsstatusprocessed (statusId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (businessId) REFERENCES xalbusiness.businesses (businessId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (userId) REFERENCES xalusers.users (userId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- contact status
-- DROP TABLE IF EXISTS xalsms.contactstatus;
-- CREATE TABLE xalsms.contactstatus (
--   statusId TINYINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
--   status VARCHAR(255) NOT NULL UNIQUE,
--   created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--   modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
--   PRIMARY KEY (statusId)
-- )ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- sms operator
DROP TABLE IF EXISTS xalsms.operator;
CREATE TABLE xalsms.operator (
  operatorId TINYINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  operator VARCHAR(255) NOT NULL UNIQUE,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (operatorId)
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- sms texts
DROP TABLE IF EXISTS xalsms.contact;
CREATE TABLE xalsms.contact (
    contactId INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    contact VARCHAR(100) NULL DEFAULT NULL UNIQUE,
    operatorId TINYINT UNSIGNED NOT NULL DEFAULT 1,
    active TINYINT UNSIGNED NOT NULL DEFAULT 1,
    valid TINYINT UNSIGNED NOT NULL DEFAULT 1,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (contactId),
    FOREIGN KEY (operatorId) REFERENCES xalsms.operator (operatorId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- sms texts
DROP TABLE IF EXISTS xalsms.contactbusiness;
CREATE TABLE xalsms.contactbusiness (
    contactId INT UNSIGNED NOT NULL,
    businessId INT UNSIGNED NOT NULL,
    customerId INT UNSIGNED NOT NULL,
    active TINYINT UNSIGNED NOT NULL DEFAULT 1,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY (contactId,businessId),
    FOREIGN KEY (contactId) REFERENCES xalsms.contact (contactId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (businessId) REFERENCES xalbusiness.businesses (businessId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (customerId) REFERENCES xalcustomers.customer (customerId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- sms texts
DROP TABLE IF EXISTS xalsms.smscontact;
CREATE TABLE xalsms.smscontact (
    smsId INT UNSIGNED NOT NULL DEFAULT 1,
    contactId INT UNSIGNED NULL DEFAULT NULL,
    contact BIGINT UNSIGNED NULL DEFAULT NULL,
    businessId INT UNSIGNED NULL DEFAULT NULL,
    customerId INT UNSIGNED NULL DEFAULT NULL,
    statusId TINYINT UNSIGNED NOT NULL DEFAULT 1,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY (smsId,contact,businessId),
    FOREIGN KEY (smsId) REFERENCES xalsms.message (smsId) ON DELETE RESTRICT ON UPDATE RESTRICT, 
    FOREIGN KEY (contactId) REFERENCES xalsms.contact (contactId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (businessId) REFERENCES xalbusiness.businesses (businessId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (customerId) REFERENCES xalcustomers.customer (customerId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- sms balance
DROP TABLE IF EXISTS xalsms.smsbalance;
CREATE TABLE xalsms.smsbalance (
    smsbalanceId INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    paymentId INT UNSIGNED NULL DEFAULT NULL UNIQUE,
    smsId INT UNSIGNED NULL DEFAULT NULL UNIQUE,
    businessId INT UNSIGNED NOT NULL,
    userId INT UNSIGNED NOT NULL,
    smsno INT UNSIGNED NOT NULL DEFAULT 0,
    addsms INT UNSIGNED NOT NULL DEFAULT 0,
    subsms INT UNSIGNED NOT NULL DEFAULT 0,
    openingbalance INT UNSIGNED NOT NULL DEFAULT 0,
    closingbalance INT UNSIGNED NOT NULL DEFAULT 0,
    active TINYINT UNSIGNED NOT NULL DEFAULT 1,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (smsbalanceId),
    FOREIGN KEY (paymentId) REFERENCES xalpayments.payments (paymentId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (smsId) REFERENCES xalsms.message (smsId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (businessId) REFERENCES xalbusiness.businesses (businessId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (userId) REFERENCES xalusers.users (userId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- sms template
DROP TABLE IF EXISTS xalsms.templates;
CREATE TABLE xalsms.templates (
    templateId INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    title VARCHAR(255) NOT NULL UNIQUE,
    template VARCHAR(1000) NULL DEFAULT NULL,
    active ENUM('1','0') NOT NULL DEFAULT '1',
    businessId INT UNSIGNED NOT NULL,
    userId INT UNSIGNED NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (templateId),
    FOREIGN KEY (businessId) REFERENCES xalbusiness.businesses (businessId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (userId) REFERENCES xalusers.users (userId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- sms groups
DROP TABLE IF EXISTS xalsms.contact_groups;
CREATE TABLE xalsms.contact_groups (
    groupId INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(1000) NULL DEFAULT NULL,
    active ENUM('1','0') NOT NULL DEFAULT '1',
    businessId INT UNSIGNED NOT NULL,
    userId INT UNSIGNED NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (groupId),
    FOREIGN KEY (businessId) REFERENCES xalbusiness.businesses (businessId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (userId) REFERENCES xalusers.users (userId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- sms texts
DROP TABLE IF EXISTS xalsms.groupcontacts;
CREATE TABLE xalsms.groupcontacts (
    groupId INT UNSIGNED NOT NULL DEFAULT 1,
    names VARCHAR(255) NULL DEFAULT NULL,
    contact BIGINT UNSIGNED NULL DEFAULT NULL,
    active ENUM('1','0') NOT NULL DEFAULT '1',
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY (groupId,contact),
    FOREIGN KEY (groupId) REFERENCES xalsms.contact_groups (groupId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

----- end



------------------------------------------------------------*/
--  DEPARTMENT  -  xaldepartments
------------------------------------------------------------*/

-- status
DROP TABLE IF EXISTS xaldepartments.status;
CREATE TABLE xaldepartments.status (
  statusId TINYINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  status VARCHAR(255) NOT NULL UNIQUE,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (statusId)
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- department
DROP TABLE IF EXISTS xaldepartments.department;
CREATE TABLE xaldepartments.department (
    departmentId INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    department VARCHAR(255) NOT NULL UNIQUE,
    -- statusId TINYINT UNSIGNED NOT NULL DEFAULT 1,
    -- businessId INT UNSIGNED NOT NULL,
    -- userId INT UNSIGNED NOT NULL,
    -- thirdpartycreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (departmentId)
    -- FOREIGN KEY (statusId) REFERENCES xaldepartments.status (statusId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    -- FOREIGN KEY (businessId) REFERENCES xalbusiness.businesses (businessId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    -- FOREIGN KEY (userId) REFERENCES xalusers.users (userId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- department business
DROP TABLE IF EXISTS xaldepartments.departmentbusiness;
CREATE TABLE xaldepartments.departmentbusiness (
    departmentId INT UNSIGNED NOT NULL,
    reference VARCHAR(255) NULL DEFAULT NULL,
    description VARCHAR(1000) NULL DEFAULT NULL,
    businessId INT UNSIGNED NOT NULL,
    userId INT UNSIGNED NOT NULL,
    -- active TINYINT UNSIGNED NOT NULL DEFAULT 1,
    statusId TINYINT UNSIGNED NOT NULL DEFAULT 1,
    thirdpartycreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY (departmentId,businessId),
    UNIQUE KEY (businessId,reference),
    FOREIGN KEY (statusId) REFERENCES xaldepartments.status (statusId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (businessId) REFERENCES xalbusiness.businesses (businessId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (userId) REFERENCES xalusers.users (userId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

---- end




------------------------------------------------------------*/
--  PRODUCT  -  xalproducts
------------------------------------------------------------*/

-- status 
DROP TABLE IF EXISTS xalproducts.status;
CREATE TABLE xalproducts.status (
  statusId TINYINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  status VARCHAR(255) NOT NULL UNIQUE,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (statusId)
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- product
DROP TABLE IF EXISTS xalproducts.product;
CREATE TABLE xalproducts.product (
    productId INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    product VARCHAR(1000) NOT NULL UNIQUE,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (productId)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- category
DROP TABLE IF EXISTS xalproducts.category;
CREATE TABLE xalproducts.category (
    categoryId INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    category VARCHAR(1000) NOT NULL UNIQUE,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (categoryId)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- categorybusiness
DROP TABLE IF EXISTS xalproducts.categorybusiness;
CREATE TABLE xalproducts.categorybusiness (
    categoryId INT UNSIGNED NOT NULL,
    reference VARCHAR(255) NULL DEFAULT NULL,
    description VARCHAR(1000) NULL DEFAULT NULL,
    businessId INT UNSIGNED NOT NULL,
    userId INT UNSIGNED NOT NULL,
    departmentId INT UNSIGNED NULL DEFAULT NULL,
    parentId INT UNSIGNED NULL DEFAULT NULL,
    active TINYINT UNSIGNED NOT NULL DEFAULT 1,
    statusId TINYINT UNSIGNED NOT NULL DEFAULT 1,
    thirdpartycreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY (categoryId,businessId),
    UNIQUE KEY (categoryId,businessId,departmentId),
    UNIQUE KEY (businessId,reference),
    FOREIGN KEY (statusId) REFERENCES xalproducts.status (statusId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (businessId) REFERENCES xalbusiness.businesses (businessId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (userId) REFERENCES xalusers.users (userId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (parentId) REFERENCES categorybusiness (categoryId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- productbusiness
DROP TABLE IF EXISTS xalproducts.productbusiness;
CREATE TABLE xalproducts.productbusiness (
    productId INT UNSIGNED NOT NULL,
    reference VARCHAR(255) NULL DEFAULT NULL,
    description VARCHAR(1000) NULL DEFAULT NULL,
    businessId INT UNSIGNED NOT NULL,
    userId INT UNSIGNED NOT NULL,
    departmentId INT UNSIGNED NULL DEFAULT NULL,
    parentId INT UNSIGNED NULL DEFAULT NULL,
    categoryId INT UNSIGNED NULL DEFAULT NULL,
    price DOUBLE UNSIGNED NULL DEFAULT NULL,
    stock INT UNSIGNED NULL DEFAULT NULL,
    active TINYINT UNSIGNED NOT NULL DEFAULT 1,
    statusId TINYINT UNSIGNED NOT NULL DEFAULT 1,
    thirdpartycreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY (productId,businessId),
    UNIQUE KEY (productId,businessId,departmentId),
    UNIQUE KEY (businessId,reference),
    FOREIGN KEY (statusId) REFERENCES xalproducts.status (statusId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (businessId) REFERENCES xalbusiness.businesses (businessId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (userId) REFERENCES xalusers.users (userId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (parentId) REFERENCES productbusiness (productId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;




------------------------------------------------------------*/
--  ROLES  -  xalroles
------------------------------------------------------------*/

-- status 
DROP TABLE IF EXISTS xalroles.role;
CREATE TABLE xalroles.role (
  roleId INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  reference VARCHAR(255) NULL DEFAULT NULL,
  role VARCHAR(255) NOT NULL UNIQUE,
  description VARCHAR(1000) NULL DEFAULT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (roleId)
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- permission
DROP TABLE IF EXISTS xalroles.permission;
CREATE TABLE xalroles.permission (
    permissionId INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    reference VARCHAR(255) NULL DEFAULT NULL,
    permission VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(1000) NULL DEFAULT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (permissionId)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- role permission business
DROP TABLE IF EXISTS xalroles.rolepermission;
CREATE TABLE xalroles.rolepermission (
    roleId INT UNSIGNED NULL DEFAULT NULL,
    permissionId INT UNSIGNED NULL DEFAULT NULL,
    description VARCHAR(1000) NULL DEFAULT NULL,
    businessId INT UNSIGNED NOT NULL,
    userId INT UNSIGNED NOT NULL,
    statusId TINYINT UNSIGNED NOT NULL DEFAULT 1,
    thirdpartycreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY (roleId,permissionId,businessId),
    FOREIGN KEY (roleId) REFERENCES xalroles.role (roleId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (permissionId) REFERENCES xalroles.permission (permissionId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (statusId) REFERENCES xalproducts.status (statusId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (businessId) REFERENCES xalbusiness.businesses (businessId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (userId) REFERENCES xalusers.users (userId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- role user business
DROP TABLE IF EXISTS xalroles.userpermission;
CREATE TABLE xalroles.userpermission (
    roleId INT UNSIGNED NULL DEFAULT NULL,
    description VARCHAR(1000) NULL DEFAULT NULL,
    businessId INT UNSIGNED NOT NULL,
    adminId INT UNSIGNED NULL DEFAULT NULL,
    userId INT UNSIGNED NOT NULL,
    statusId TINYINT UNSIGNED NOT NULL DEFAULT 1,
    thirdpartycreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY (roleId,businessId,userId),
    FOREIGN KEY (roleId) REFERENCES xalroles.role (roleId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (statusId) REFERENCES xalproducts.status (statusId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (businessId) REFERENCES xalbusiness.businesses (businessId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (userId) REFERENCES xalusers.users (userId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (adminId) REFERENCES xalusers.users (userId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;




------------------------------------------------------------*/
--  ACCOUNTING  -  xalaccounting
------------------------------------------------------------*/


-- status 
DROP TABLE IF EXISTS xalaccounting.status;
CREATE TABLE xalaccounting.status (
  statusId TINYINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  status VARCHAR(255) NOT NULL UNIQUE,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (statusId)
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;


-- chart of accounts 
DROP TABLE IF EXISTS xalaccounting.accountsmaincategory;
CREATE TABLE xalaccounting.accountsmaincategory (
  accountId INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  account VARCHAR(255) NULL DEFAULT NULL,
  entrytype ENUM('debit','credit') NOT NULL,
  description VARCHAR(1000) NULL DEFAULT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (accountId)
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;


-- cashflow categories
DROP TABLE IF EXISTS xalaccounting.cashflowcategories;
CREATE TABLE xalaccounting.cashflowcategories (
  categoryId TINYINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  category VARCHAR(255) NOT NULL UNIQUE,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (categoryId)
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;


-- chart of accounts
DROP TABLE IF EXISTS xalaccounting.accounts;
CREATE TABLE xalaccounting.accounts (
    accountId INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    account VARCHAR(255) NULL DEFAULT NULL,
    categoryId INT UNSIGNED NOT NULL,
    parentId INT UNSIGNED NULL DEFAULT NULL,
    accountcode VARCHAR(255) NULL DEFAULT NULL,
    businessId INT UNSIGNED NOT NULL,
    description VARCHAR(1000) NULL DEFAULT NULL,
    userId INT UNSIGNED NOT NULL,
    statusId TINYINT UNSIGNED NOT NULL DEFAULT 1,
    postable TINYINT UNSIGNED NOT NULL DEFAULT 1,
    entrytype ENUM('debit','credit') NOT NULL,
    debit DOUBLE NOT NULL DEFAULT 0,
    credit DOUBLE NOT NULL DEFAULT 0,
    thirdpartycreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (accountId),
    FOREIGN KEY (categoryId) REFERENCES xalaccounting.accountsmaincategory (accountId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (statusId) REFERENCES xalaccounting.status (statusId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (businessId) REFERENCES xalbusiness.businesses (businessId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (userId) REFERENCES xalusers.users (userId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (parentId) REFERENCES xalaccounting.accounts (accountId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;
ALTER TABLE xalaccounting.accounts
    ADD COLUMN debit DOUBLE NOT NULL DEFAULT 0 AFTER entrytype,
    ADD COLUMN credit DOUBLE NOT NULL DEFAULT 0 AFTER debit,
    ADD COLUMN balance DOUBLE NOT NULL DEFAULT 0 AFTER credit;
ALTER TABLE xalaccounting.accounts
    ADD COLUMN cashflowstatement TINYINT UNSIGNED NOT NULL DEFAULT 0 AFTER credit,
    ADD COLUMN incomestatement TINYINT UNSIGNED NOT NULL DEFAULT 0 AFTER cashflowstatement,
    ADD COLUMN balancesheetstatement TINYINT UNSIGNED NOT NULL DEFAULT 0 AFTER incomestatement;
ALTER TABLE xalaccounting.accounts
    ADD COLUMN cashflowcategoryId TINYINT UNSIGNED NULL DEFAULT NULL AFTER cashflowstatement,
    ADD CONSTRAINT FOREIGN KEY (cashflowcategoryId) REFERENCES xalaccounting.cashflowcategories (categoryId) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE xalaccounting.accounts
    ADD UNIQUE KEY (account,businessId);


-- journals
DROP TABLE IF EXISTS xalaccounting.journals;
CREATE TABLE xalaccounting.journals (
    journalId INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    reference VARCHAR(255) NULL DEFAULT NULL,
    posted ENUM('0','1') NOT NULL,
    description VARCHAR(1000) NULL DEFAULT NULL,
    userId INT UNSIGNED NOT NULL,
    businessId INT UNSIGNED NOT NULL,    
    posteddate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    thirdpartycreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (journalId),
    FOREIGN KEY (businessId) REFERENCES xalbusiness.businesses (businessId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (userId) REFERENCES xalusers.users (userId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;


-- transactions
DROP TABLE IF EXISTS xalaccounting.transactions;
CREATE TABLE xalaccounting.transactions (
    transactionId INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    journalId INT UNSIGNED NOT NULL,
    accountId INT UNSIGNED NOT NULL,
    description VARCHAR(1000) NULL DEFAULT NULL,
    debit DOUBLE NOT NULL DEFAULT 0,
    credit DOUBLE NOT NULL DEFAULT 0,
    balance DOUBLE NOT NULL DEFAULT 0,
    active ENUM('0','1') NOT NULL DEFAULT '1',
    visible ENUM('0','1') NOT NULL DEFAULT '1',
    userId INT UNSIGNED NOT NULL,
    thirdpartycreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (transactionId),
    FOREIGN KEY (journalId) REFERENCES xalaccounting.journals (journalId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (accountId) REFERENCES xalaccounting.accounts (accountId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (userId) REFERENCES xalusers.users (userId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;
ALTER TABLE xalaccounting.transactions
    ADD COLUMN visible ENUM('0','1') NOT NULL DEFAULT '1' AFTER active;


-- ledgers
DROP TABLE IF EXISTS xalaccounting.ledgers;
CREATE TABLE xalaccounting.ledgers (
    ledgerId INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    journalId INT UNSIGNED NOT NULL,
    accountId INT UNSIGNED NOT NULL,
    description VARCHAR(1000) NULL DEFAULT NULL,
    opening DOUBLE NOT NULL DEFAULT 0,
    debit DOUBLE NOT NULL DEFAULT 0,
    credit DOUBLE NOT NULL DEFAULT 0,
    closing DOUBLE NOT NULL DEFAULT 0,
    active ENUM('0','1') NOT NULL,
    userId INT UNSIGNED NOT NULL,
    businessId INT UNSIGNED NOT NULL,
    thirdpartycreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ledgerId),
    FOREIGN KEY (accountId) REFERENCES xalaccounting.accounts (accountId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (journalId) REFERENCES xalaccounting.journals (journalId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (userId) REFERENCES xalusers.users (userId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (businessId) REFERENCES xalbusiness.businesses (businessId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;
ALTER TABLE ledgers
    ADD COLUMN journalId INT UNSIGNED NOT NULL AFTER ledgerId,
    ADD CONSTRAINT FOREIGN KEY journalId REFERENCES journals (journalId) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE xalaccounting.ledgers
    ADD COLUMN visible ENUM('0','1') NOT NULL DEFAULT '1' AFTER active;


-- role user business
DROP TABLE IF EXISTS xalaccounting.accountsbusiness;
CREATE TABLE xalaccounting.accountsbusiness (
    accountId INT UNSIGNED NULL DEFAULT NULL,
    businessId INT UNSIGNED NOT NULL,
    description VARCHAR(1000) NULL DEFAULT NULL,
    userId INT UNSIGNED NOT NULL,
    active ENUM('0','1') NOT NULL,
    thirdpartycreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY (accountId,businessId),
    FOREIGN KEY (accountId) REFERENCES xalaccounting.accounts (accountId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (businessId) REFERENCES xalbusiness.businesses (businessId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (userId) REFERENCES xalusers.users (userId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;


-- REPORTS
-- 1. Income ( P&L ) statement
-- 2. Cash flow
-- 3. Cash book

-- 3. General ledger
-- 4. Trial balance
-- 5. Balance sheet

-- 6. Statement of shareholder's equity


-- status 
DROP TABLE IF EXISTS xalusers.status;
CREATE TABLE xalusers.status (
  statusId TINYINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  status VARCHAR(255) NOT NULL UNIQUE,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (statusId)
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- user roles
DROP TABLE IF EXISTS xalusers.userroles;
CREATE TABLE xalusers.userroles (
    roleId INT UNSIGNED NOT NULL,
    description VARCHAR(1000) NULL DEFAULT NULL,
    adminId INT UNSIGNED NOT NULL,
    userId INT UNSIGNED NOT NULL,
    statusId TINYINT UNSIGNED NOT NULL DEFAULT 1,
    businessId INT UNSIGNED NOT NULL,
    thirdpartycreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY (roleId,userId,businessId),
    FOREIGN KEY (roleId) REFERENCES xalroles.role (roleId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (adminId) REFERENCES xalusers.users (userId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (userId) REFERENCES xalusers.users (userId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (statusId) REFERENCES xalusers.status (statusId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (businessId) REFERENCES xalbusiness.businesses (businessId) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;